---
# this is the config that will be loaded as default by main.py
# Please follow the provided structure (this will ensuring all baseline follow
# a similar configuration structure and hence be easy to customise)

num_clients: 4
num_epochs: 1
batch_size: 10
clients_per_round: 2
fraction_fit: 0.1
learning_rate: 0.001
num_rounds: 2
partitioning: "imbalance_label" #imbalance_label, imbalance_label_dirichlet, noise_based_imbalance, quantity_skew_dirichlet
dataset_name: "chest_xray"
dataset_seed: 42
alpha: 0.5
sigma: 0.1
labels_per_client: 2 # only used when partitioning is label quantity
momentum: 0.9
weight_decay: 0.00001

client_fn:
  _target_: niid_bench.client_fedavg.gen_client_fn
  _recursive_: False
  num_epochs: ${num_epochs}
  learning_rate: ${learning_rate}
  momentum: ${momentum}
  weight_decay: ${weight_decay}

dataset:
  # dataset config
  name: ${dataset_name}
  partitioning: ${partitioning}
  batch_size: ${batch_size} # batch_size = batch_size_ratio * total_local_data_size
  val_split: 0.1
  seed: ${dataset_seed}
  alpha: ${alpha}
  labels_per_client: ${labels_per_client}
  sigma: ${sigma}

model:
  # model config
  _target_: niid_bench.models.ResNet18Model
  # input_dim: 10000
  # hidden_dims: [120, 84]
  num_classes: 2

strategy:
  _target_: flwr.server.strategy.FedAvg # points to your strategy (either custom or exiting in Flower)
  # rest of strategy config
  fraction_fit: ${fraction_fit} # because we want the number of clients to sample on each round to be solely defined by min_fit_clients
  fraction_evaluate: 0.0
  min_fit_clients: ${clients_per_round}
  min_available_clients: ${clients_per_round}
  min_evaluate_clients: 0

client:
  # client config

server_device: cpu

client_resources:
  num_cpus: 6
  num_gpus: 0.5
